import type { RadarControlCenterData } from "./contracts";

export const radarFixture = {
  generatedAt: "2026-08-24T10:42:00.000Z",
  metrics: {
    runsToday: 12,
    publishedThisWeek: 8,
    rejectedThisWeek: 19,
    successRate: 96.4,
    averageDuration: "3m 18s",
  },
  runs: [
    {
      id: "run-2408-042",
      candidateId: "candidate-agent-governance",
      engineRunId: "radar-2026-08-24-042",
      outcome: "PUBLISHED",
      startedAt: "2026-08-24T10:31:00.000Z",
      finishedAt: "2026-08-24T10:35:12.000Z",
      duration: "4m 12s",
      source: "OpenAI Newsroom",
      title: "Gobernanza práctica para agentes de IA en producción",
      scoreTotal: 92,
    },
    {
      id: "run-2408-041",
      candidateId: "candidate-crm-release",
      engineRunId: "radar-2026-08-24-041",
      outcome: "REJECTED",
      startedAt: "2026-08-24T09:48:00.000Z",
      finishedAt: "2026-08-24T09:49:44.000Z",
      duration: "1m 44s",
      source: "Product changelog",
      title: "Actualización menor en una plataforma CRM",
      scoreTotal: 61,
    },
    {
      id: "run-2408-040",
      candidateId: "candidate-data-ops",
      engineRunId: "radar-2026-08-24-040",
      outcome: "PUBLISHED",
      startedAt: "2026-08-24T08:56:00.000Z",
      finishedAt: "2026-08-24T09:01:06.000Z",
      duration: "5m 06s",
      source: "Google Cloud Blog",
      title: "Data operations: del reporte manual al circuito confiable",
      scoreTotal: 89,
    },
    {
      id: "run-2408-039",
      candidateId: "candidate-whatsapp",
      engineRunId: "radar-2026-08-24-039",
      outcome: "REJECTED",
      startedAt: "2026-08-24T08:12:00.000Z",
      finishedAt: "2026-08-24T08:14:21.000Z",
      duration: "2m 21s",
      source: "Meta Business",
      title: "Nuevo ajuste de interfaz para campañas de WhatsApp",
      scoreTotal: 67,
    },
    {
      id: "run-2408-038",
      candidateId: "candidate-ai-infra",
      engineRunId: "radar-2026-08-24-038",
      outcome: "RUNNING",
      startedAt: "2026-08-24T10:39:00.000Z",
      duration: "3m 02s",
      source: "Microsoft Research",
      title: "Infraestructura observable para sistemas multiagente",
      scoreTotal: 87,
    },
  ],
  candidates: [
    {
      id: "candidate-agent-governance",
      engineRunId: "radar-2026-08-24-042",
      title: "Gobernanza práctica para agentes de IA en producción",
      topic: "Controles operativos para agentes autónomos",
      summary: "Una mirada aplicada a los límites, trazabilidad y circuitos de aprobación que hacen viable operar agentes de IA en procesos críticos.",
      sourceName: "OpenAI Newsroom",
      sourceUrl: "https://example.com/openai-agent-governance",
      contentPurpose: "criterio",
      territory: "ia-aplicada-empresas",
      status: "published",
      scoreTotal: 92,
      publicSignals: [
        { key: "relevance", label: "Relevancia", score: 96 },
        { key: "novelty", label: "Novedad", score: 88 },
        { key: "editorial-fit", label: "Ajuste editorial", score: 93 },
      ],
      submittedAt: "2026-08-24T10:31:00.000Z",
      decisionAt: "2026-08-24T10:35:12.000Z",
      publishedUrl: "/noticias/agentes-ia-produccion-control-limites",
    },
    {
      id: "candidate-crm-release",
      engineRunId: "radar-2026-08-24-041",
      title: "Actualización menor en una plataforma CRM",
      topic: "Cambio de interfaz sin impacto operativo comprobable",
      summary: "El cambio revisado reorganiza controles visuales, pero no modifica el flujo comercial ni aporta una mejora medible para el equipo.",
      sourceName: "Product changelog",
      sourceUrl: "https://example.com/crm-release-notes",
      contentPurpose: "actualidad",
      territory: "crm-automatizacion-comercial",
      status: "rejected",
      scoreTotal: 61,
      publicSignals: [
        { key: "relevance", label: "Relevancia", score: 72 },
        { key: "novelty", label: "Novedad", score: 41 },
        { key: "editorial-fit", label: "Ajuste editorial", score: 68 },
      ],
      submittedAt: "2026-08-24T09:48:00.000Z",
      decisionAt: "2026-08-24T09:49:44.000Z",
      rejectionReason: "Baja novedad y sin impacto operativo suficiente para una pieza editorial independiente.",
    },
    {
      id: "candidate-data-ops",
      engineRunId: "radar-2026-08-24-040",
      title: "Data operations: del reporte manual al circuito confiable",
      topic: "Automatización y trazabilidad del reporting operativo",
      summary: "Cómo diseñar una operación de datos que reduzca tareas repetitivas sin perder contexto, responsables ni capacidad de auditoría.",
      sourceName: "Google Cloud Blog",
      sourceUrl: "https://example.com/data-operations",
      contentPurpose: "seo",
      territory: "data-analytics",
      status: "published",
      scoreTotal: 89,
      publicSignals: [
        { key: "relevance", label: "Relevancia", score: 91 },
        { key: "novelty", label: "Novedad", score: 84 },
        { key: "editorial-fit", label: "Ajuste editorial", score: 92 },
      ],
      submittedAt: "2026-08-24T08:56:00.000Z",
      decisionAt: "2026-08-24T09:01:06.000Z",
      publishedUrl: "/noticias/como-automatizar-reportes-de-ventas",
    },
    {
      id: "candidate-whatsapp",
      engineRunId: "radar-2026-08-24-039",
      title: "Nuevo ajuste de interfaz para campañas de WhatsApp",
      topic: "Cambio cosmético en el administrador de campañas",
      summary: "La actualización simplifica dos pantallas, sin cambiar capacidades, integraciones ni resultados operativos.",
      sourceName: "Meta Business",
      sourceUrl: "https://example.com/whatsapp-campaign-update",
      contentPurpose: "actualidad",
      territory: "crm-automatizacion-comercial",
      status: "rejected",
      scoreTotal: 67,
      publicSignals: [
        { key: "relevance", label: "Relevancia", score: 73 },
        { key: "novelty", label: "Novedad", score: 52 },
        { key: "editorial-fit", label: "Ajuste editorial", score: 70 },
      ],
      submittedAt: "2026-08-24T08:12:00.000Z",
      decisionAt: "2026-08-24T08:14:21.000Z",
      rejectionReason: "Cambio incremental sin evidencia de impacto para equipos comerciales.",
    },
    {
      id: "candidate-ai-infra",
      engineRunId: "radar-2026-08-24-038",
      title: "Infraestructura observable para sistemas multiagente",
      topic: "Monitoreo y confiabilidad de flujos con múltiples agentes",
      summary: "Patrones de observabilidad para entender decisiones, fallas y dependencias en sistemas multiagente.",
      sourceName: "Microsoft Research",
      sourceUrl: "https://example.com/multi-agent-observability",
      contentPurpose: "criterio",
      territory: "ia-aplicada-empresas",
      status: "reviewing",
      scoreTotal: 87,
      publicSignals: [
        { key: "relevance", label: "Relevancia", score: 90 },
        { key: "novelty", label: "Novedad", score: 86 },
        { key: "editorial-fit", label: "Ajuste editorial", score: 85 },
      ],
      submittedAt: "2026-08-24T10:39:00.000Z",
    },
  ],
  audit: [
    {
      id: "audit-101",
      occurredAt: "2026-08-24T10:35:12.000Z",
      event: "Publicación verificada",
      detail: "URL canónica, Open Graph y portada respondieron correctamente.",
      actor: "Deployment Gate",
      reference: "radar-2026-08-24-042",
      tone: "success",
    },
    {
      id: "audit-100",
      occurredAt: "2026-08-24T10:33:48.000Z",
      event: "Materialización completada",
      detail: "Artículo y portada incorporados como un cambio atómico.",
      actor: "Content Pipeline",
      reference: "radar-2026-08-24-042",
      tone: "info",
    },
    {
      id: "audit-099",
      occurredAt: "2026-08-24T09:49:44.000Z",
      event: "Candidato rechazado",
      detail: "Decisión registrada en el historial privado.",
      actor: "Radar Engine",
      reference: "radar-2026-08-24-041",
      tone: "warning",
    },
    {
      id: "audit-098",
      occurredAt: "2026-08-24T09:48:22.000Z",
      event: "Evaluación completada",
      detail: "Las señales públicas quedaron normalizadas para la decisión editorial.",
      actor: "Radar Engine",
      reference: "radar-2026-08-24-041",
      tone: "neutral",
    },
    {
      id: "audit-097",
      occurredAt: "2026-08-24T09:01:06.000Z",
      event: "Publicación verificada",
      detail: "La pieza superó los controles de producción y disponibilidad pública.",
      actor: "Deployment Gate",
      reference: "radar-2026-08-24-040",
      tone: "success",
    },
    {
      id: "audit-096",
      occurredAt: "2026-08-24T08:58:41.000Z",
      event: "Gates técnicos aprobados",
      detail: "Validación, auditoría editorial y build finalizaron sin errores.",
      actor: "Content Pipeline",
      reference: "radar-2026-08-24-040",
      tone: "info",
    },
    {
      id: "audit-095",
      occurredAt: "2026-08-24T08:14:21.000Z",
      event: "Candidato rechazado",
      detail: "Decisión registrada sin crear rama ni PR de contenido.",
      actor: "Radar Engine",
      reference: "radar-2026-08-24-039",
      tone: "warning",
    },
  ],
} satisfies RadarControlCenterData;
