import type { RadarControlCenterData } from "./contracts";

export const radarFixture = {
  generatedAt: "2026-08-24T10:42:00.000Z",
  status: {
    state: "working",
    title: "Radar está buscando nuevas oportunidades",
    detail:
      "Está revisando fuentes oficiales y reconocidas sobre los temas que priorizaste.",
  },
  summary: {
    detectedThisWeek: 14,
    publishedThisWeek: 4,
    trackingNow: 6,
    discardedThisWeek: 4,
    attentionRequired: 1,
  },
  opportunities: [
    {
      id: "agent-governance",
      title: "Gobernanza práctica para agentes de IA en producción",
      topic: "Controles operativos para agentes autónomos",
      category: "IA aplicada",
      summary:
        "Una oportunidad para explicar cómo operar agentes con límites claros, trazabilidad y control humano.",
      sourceName: "OpenAI Newsroom",
      sourceUrl: "https://openai.com/news/",
      detectedAt: "2026-08-24T10:31:00.000Z",
      potential: "high",
      status: "published",
      explanation:
        "Combina actualidad, autoridad de fuente y una pregunta concreta que ya preocupa a empresas que adoptan IA.",
      businessSignal: "Puede reforzar autoridad y captar búsquedas de alta intención.",
      imageUrl: "/assets/insights/cover-gobernanza-ia.jpg",
      publicScore: 92,
      technicalReference: "radar-2026-08-24-042",
      publicationId: "publication-governance",
    },
    {
      id: "multi-agent-observability",
      title: "Infraestructura observable para sistemas multiagente",
      topic: "Confiabilidad de flujos con múltiples agentes",
      category: "Infraestructura de IA",
      summary:
        "Patrones para entender decisiones, fallas y dependencias en operaciones impulsadas por agentes.",
      sourceName: "Microsoft Research",
      sourceUrl: "https://www.microsoft.com/en-us/research/",
      detectedAt: "2026-08-24T10:39:00.000Z",
      potential: "high",
      status: "review",
      explanation:
        "El tema tiene gran potencial, pero su nivel técnico exige una última revisión de enfoque antes de convertirlo en contenido.",
      businessSignal: "Abre una conversación valiosa con equipos que ya escalaron sus pruebas de IA.",
      imageUrl: "/assets/insights/cover-infraestructura-ia.jpg",
      publicScore: 87,
      technicalReference: "radar-2026-08-24-038",
    },
    {
      id: "data-operations",
      title: "Data operations: del reporte manual al circuito confiable",
      topic: "Automatización del reporting operativo",
      category: "Data & Analytics",
      summary:
        "Cómo reducir tareas repetitivas sin perder contexto, responsables ni capacidad de auditoría.",
      sourceName: "Google Cloud",
      sourceUrl: "https://cloud.google.com/blog/",
      detectedAt: "2026-08-24T08:56:00.000Z",
      potential: "high",
      status: "published",
      explanation:
        "Resuelve un dolor frecuente y conecta con una búsqueda comercial clara: automatizar reportes sin perder control.",
      businessSignal: "Tiene utilidad inmediata para operaciones, ventas y finanzas.",
      imageUrl: "/assets/insights/cover-reportes-ventas.jpg",
      publicScore: 89,
      technicalReference: "radar-2026-08-24-040",
      publicationId: "publication-data-ops",
    },
    {
      id: "automation-playbook",
      title: "El playbook para detectar automatizaciones que sí valen la pena",
      topic: "Priorización de procesos",
      category: "Automatización",
      summary:
        "Un marco práctico para separar procesos automatizables de iniciativas que sólo agregan complejidad.",
      sourceName: "Harvard Business Review",
      sourceUrl: "https://hbr.org/",
      detectedAt: "2026-08-23T16:20:00.000Z",
      potential: "high",
      status: "ready",
      explanation:
        "Tiene encaje directo con la propuesta de NexOps y permite convertir criterio operativo en una pieza accionable.",
      businessSignal: "Puede atraer responsables que están definiendo su hoja de ruta de automatización.",
      imageUrl: "/assets/insights/cover-proceso-roto.jpg",
      publicScore: 90,
      technicalReference: "radar-2026-08-23-036",
    },
    {
      id: "whatsapp-update",
      title: "WhatsApp incorpora nuevas señales para conversaciones comerciales",
      topic: "Automatización comercial",
      category: "CRM & Ventas",
      summary:
        "Cambios que podrían mejorar el seguimiento de conversaciones, todavía sin evidencia suficiente de impacto real.",
      sourceName: "Meta Business",
      sourceUrl: "https://www.facebook.com/business/news",
      detectedAt: "2026-08-23T14:10:00.000Z",
      potential: "medium",
      status: "tracking",
      explanation:
        "Es relevante para el público objetivo, aunque Radar espera evidencia más concreta antes de avanzar.",
      businessSignal: "Podría convertirse en una guía útil si aparecen casos de adopción verificables.",
      imageUrl: "/assets/insights/cover-meta-business-agent.jpg",
      publicScore: 76,
      technicalReference: "radar-2026-08-23-035",
    },
    {
      id: "minor-crm-release",
      title: "Actualización menor en una plataforma CRM",
      topic: "Cambio de interfaz",
      category: "CRM & Ventas",
      summary:
        "Una reorganización visual sin mejoras comprobables en el flujo comercial ni en los resultados del equipo.",
      sourceName: "Product changelog",
      sourceUrl: "https://example.com/crm-release-notes",
      detectedAt: "2026-08-24T09:48:00.000Z",
      potential: "low",
      status: "discarded",
      explanation:
        "El cambio es demasiado incremental y no aporta una idea suficientemente útil para publicar.",
      businessSignal: "Descartarla protege el foco editorial y evita sumar ruido.",
      imageUrl: "/assets/insights/cover-whatsapp-crm-guia.jpg",
      publicScore: 61,
      technicalReference: "radar-2026-08-24-041",
    },
  ],
  publications: [
    {
      id: "publication-governance",
      opportunityId: "agent-governance",
      title: "Gobernanza práctica para agentes de IA en producción",
      category: "IA aplicada",
      publishedAt: "2026-08-24T10:35:12.000Z",
      url: "/noticias/agentes-ia-produccion-control-limites",
      imageUrl: "/assets/insights/cover-gobernanza-ia.jpg",
      reason:
        "Radar detectó una conversación emergente con alto valor para líderes que están incorporando agentes.",
      origin: "automatic",
      status: "verified",
    },
    {
      id: "publication-data-ops",
      opportunityId: "data-operations",
      title: "Data operations: del reporte manual al circuito confiable",
      category: "Data & Analytics",
      publishedAt: "2026-08-24T09:01:06.000Z",
      url: "/noticias/como-automatizar-reportes-de-ventas",
      imageUrl: "/assets/insights/cover-reportes-ventas.jpg",
      reason:
        "La oportunidad combinó demanda sostenida, impacto operativo y un enfoque claramente accionable.",
      origin: "automatic",
      status: "verified",
    },
    {
      id: "publication-automation",
      opportunityId: "automation-playbook",
      title: "Cómo identificar un proceso roto antes de automatizarlo",
      category: "Automatización",
      publishedAt: "2026-08-21T12:14:00.000Z",
      url: "/noticias/como-identificar-un-proceso-roto-antes-de-automatizarlo",
      imageUrl: "/assets/insights/cover-proceso-roto.jpg",
      reason:
        "Respondía una pregunta recurrente de negocio y permitía aportar un método propio sin exponer la inteligencia interna.",
      origin: "automatic",
      status: "verified",
    },
  ],
  configuration: {
    goals: [
      {
        id: "organic-demand",
        label: "Atraer demanda orgánica",
        description: "Crear contenido útil para búsquedas con intención de negocio.",
        priority: "primary",
      },
      {
        id: "freshness",
        label: "Mantener la marca vigente",
        description: "Participar en conversaciones nuevas cuando realmente importan.",
        priority: "secondary",
      },
      {
        id: "commercial",
        label: "Abrir conversaciones comerciales",
        description: "Priorizar problemas vinculados con servicios de NexOps.",
        priority: "secondary",
      },
      {
        id: "authority",
        label: "Construir autoridad temática",
        description: "Profundizar en territorios donde NexOps quiere ser referencia.",
        priority: "off",
      },
    ],
    topics: [
      { id: "applied-ai", label: "IA aplicada", enabled: true },
      { id: "automation", label: "Automatización", enabled: true },
      { id: "crm", label: "CRM & Ventas", enabled: true },
      { id: "data", label: "Data & Analytics", enabled: true },
      { id: "cybersecurity", label: "Ciberseguridad", enabled: false },
    ],
    selectivity: "balanced",
    autonomy: "automatic",
    sourcePreference: "recognized",
    restrictions: [
      {
        id: "no-clients",
        label: "No mencionar clientes",
        description: "Evita usar nombres o casos de clientes sin autorización.",
        enabled: true,
      },
      {
        id: "primary-source",
        label: "Confirmar con una fuente directa",
        description: "Exige respaldo oficial antes de avanzar con una publicación.",
        enabled: true,
      },
      {
        id: "image-required",
        label: "Publicar sólo con una imagen adecuada",
        description: "Detiene la oportunidad si no hay una portada coherente.",
        enabled: true,
      },
      {
        id: "blocked-topics",
        label: "Excluir comparaciones agresivas",
        description: "Evita contenido que ataque marcas o competidores.",
        enabled: false,
      },
    ],
    maximumPerWeek: 4,
    enabledDays: ["Lun", "Mar", "Mié", "Jue"],
    avoidSimilarTopics: true,
  },
  history: [
    {
      id: "history-101",
      occurredAt: "2026-08-24T10:35:12.000Z",
      title: "Una nueva publicación quedó disponible",
      detail:
        "Gobernanza práctica para agentes de IA superó los controles y ya está publicada.",
      tone: "success",
      technicalReference: "radar-2026-08-24-042",
    },
    {
      id: "history-100",
      occurredAt: "2026-08-24T10:39:00.000Z",
      title: "Una oportunidad necesita atención",
      detail:
        "Infraestructura observable para sistemas multiagente requiere una revisión de enfoque.",
      tone: "attention",
      technicalReference: "radar-2026-08-24-038",
    },
    {
      id: "history-099",
      occurredAt: "2026-08-24T09:49:44.000Z",
      title: "Radar decidió no publicar una actualización menor",
      detail:
        "La novedad del CRM no mostraba impacto suficiente para la audiencia de NexOps.",
      tone: "neutral",
      technicalReference: "radar-2026-08-24-041",
    },
    {
      id: "history-098",
      occurredAt: "2026-08-24T09:01:06.000Z",
      title: "Data operations fue publicado",
      detail:
        "La pieza quedó disponible después de validar su utilidad, fuente y presentación.",
      tone: "success",
      technicalReference: "radar-2026-08-24-040",
    },
    {
      id: "history-097",
      occurredAt: "2026-08-23T14:14:21.000Z",
      title: "Radar sigue observando un cambio de WhatsApp",
      detail:
        "Todavía no hay evidencia suficiente de impacto comercial para convertirlo en contenido.",
      tone: "info",
      technicalReference: "radar-2026-08-23-035",
    },
  ],
} satisfies RadarControlCenterData;
